### PR TITLE
Revert "Fix unexpected token with"

### PR DESCRIPTION
**Pull request by ryoppippi**
Reverts ryoppippi/unplugin-typia#189

import assertion is not allowed in JSR

### CODE REVIEW

**Comment by ryoppippi** [comment]
@picode7 So try use node >= 20

**Comment by picode7** [comment]
hm, I'm actually using v20.11.0

**Comment by picode7** [comment]
and it doesn't complain when putting it into my own code. Maybe the issue is coming with Svelte or Vite then?

```
import typiaPackageJson from 'typia/package.json' with { type: 'json' }
console.log(typiaPackageJson)
```

**Comment by ryoppippi** [comment]
@picode7 
Hi, thank you for your investigation.
I changed the way to parse `Typia`'s package.json .
https://github.com/ryoppippi/unplugin-typia/pull/216
So there should not be an error.
Please update this lib and try it!'

**Pull request merged**
